Mosqueapp/Models/LanguageInput.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mosqueapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageInput
    {
        public int LanguageInputId { get; set; }
        public string Language { get; set; }
    }
}

Mosqueapp/Controllers/LanguageInputsController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mosqueapp.Models;

namespace Mosqueapp.Controllers
{
    public class LanguageInputsController : Controller
    {
        private mosqueappEntities db = new mosqueappEntities();

        // GET: LanguageInputs
        public ActionResult Index()
        {
            //ReadOnlyCollection<TimeZoneInfo> timeZones = TimeZoneInfo.GetSystemTimeZones();

            //foreach (TimeZoneInfo timeZone in timeZones)
            //{
            //    // store whatever you need to store to a SQL Server table
            //}
            var languageInputs = db.LanguageInputs;
            return View(languageInputs.ToList());
        }

        // GET: LanguageInputs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LanguageInput languageInput = db.LanguageInputs.Find(id);
            if (languageInput == null)
            {
                return HttpNotFound();
            }
            return View(languageInput);
        }

        // GET: LanguageInputs/Create
        public ActionResult Create()
        {
            ViewBag.LanguageInputId = new SelectList(db.Masjids, "Masjidid", "Masjidname");
            return View();
        }

        // POST: LanguageInputs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LanguageInputId,Language")] LanguageInput languageInput)
        {
            if (ModelState.IsValid)
            {
                db.LanguageInputs.Add(languageInput);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LanguageInputId = new SelectList(db.Masjids, "Masjidid", "Masjidname", languageInput.LanguageInputId);
            return View(languageInput);
        }

        // GET: LanguageInputs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LanguageInput languageInput = db.LanguageInputs.Find(id);
            if (languageInput == null)
            {
                return HttpNotFound();
            }
            ViewBag.LanguageInputId = new SelectList(db.Masjids, "Masjidid", "Masjidname", languageInput.LanguageInputId);
            return View(languageInput);
        }

        // POST: LanguageInputs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LanguageInputId,Language")] LanguageInput languageInput)
        {
            if (ModelState.IsValid)
            {
                db.Entry(languageInput).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LanguageInputId = new SelectList(db.Masjids, "Masjidid", "Masjidname", languageInput.LanguageInputId);
            return View(languageInput);
        }

        // GET: LanguageInputs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LanguageInput languageInput = db.LanguageInputs.Find(id);
            if (languageInput == null)
            {
                return HttpNotFound();
            }
            return View(languageInput);
        }

        // POST: LanguageInputs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LanguageInput languageInput = db.LanguageInputs.Find(id);
            db.LanguageInputs.Remove(languageInput);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mosqueapp/Views/LanguageInputs/Create.cshtml
@model Mosqueapp.Models.LanguageInput

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LanguageInput</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mosqueapp/Views/LanguageInputs/Delete.cshtml
@model Mosqueapp.Models.LanguageInput

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LanguageInput</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Masjid.Masjidname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Masjid.Masjidname)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Mosqueapp/Views/LanguageInputs/Details.cshtml
@model Mosqueapp.Models.LanguageInput

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>LanguageInput</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Masjid.Masjidname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Masjid.Masjidname)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LanguageInputId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Mosqueapp/Views/LanguageInputs/Edit.cshtml
@model Mosqueapp.Models.LanguageInput

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LanguageInput</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LanguageInputId)

        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mosqueapp/Views/LanguageInputs/Index.cshtml
@model IEnumerable<Mosqueapp.Models.LanguageInput>

@{
    ViewBag.Title = "Language List";
    Layout = "~/Views/Shared/_Layout.cshtml";

    WebGrid webGrid = new WebGrid(Model);
}

<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .Grid {
        border: 1px solid #ccc;
        border-collapse: collapse;
    }

        .Grid th {
            background-color: #F7F7F7;
            font-weight: bold;
        }

        .Grid th, .Grid td {
            padding: 5px;
            border: 1px solid #ccc;
        }

        .Grid, .Grid table td {
            border: 0px solid #ccc;
        }

            .Grid th a, .Grid th a:visited {
                color: #333;
            }
</style>
<h4>Language List</h4>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

@webGrid.GetHtml(
    tableStyle: "table table-bordered table-striped mr",
    rowStyle: "gridrow",
    alternatingRowStyle: "gridalt",
        htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
        columns: webGrid.Columns(
                 webGrid.Column("Language", "Language"),
                 webGrid.Column(columnName: "", format: (item) => Html.ActionLink("Edit", "Edit", "LanguageInputs",
new { id = item.LanguageInputId }, null)),
webGrid.Column(columnName: "", format: (item) => Html.ActionLink("Delete", "Delete", "LanguageInputs",
new { id = item.LanguageInputId }, null))

))