Mosqueapp/Controllers/MosqueController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Mosqueapp.common;
using Mosqueapp.Models;

namespace Mosqueapp.Controllers
{
    public class MosqueController : Controller
    {
        private mosqueappEntities db = new mosqueappEntities();
        // GET: Mosque
        public ActionResult Index()
        {
            List<mosquevm> lst = new List<mosquevm>();
            var input = db.Masjids.ToList();
            var languages = db.LanguageInputs.ToList();
            var prayertimes = db.Prayertimes.ToList();
            foreach(var data in input)
            {
                mosquevm obj = new mosquevm();
                obj.Masjidid = data.Masjidid;
                obj.Masjidname = data.Masjidname;
                obj.Language = languages.Where(x => x.LanguageInputId == data.Languageid.Value).First().Language;
                obj.Cityname = data.Cityname;
                obj.Designlayout = data.IsHorizontal.Value ? "Horizontal" : "Vertical";
                obj.Designname = data.Designname;
                obj.Prayertimeid = data.Prayertimeid.Value;
                if (data.IsHorizontal.Value)
                {
                    obj.Imagepath = "~/HorizontalDesign/" + obj.Designname + ".jpg";
                }
                else
                {
                    obj.Imagepath = "~/VerticalDesign/" + obj.Designname + ".jpg";
                }
                lst.Add(obj);
            }

            return View(lst);
        }

        public ActionResult Create()
        {
            ViewBag.LanguageInputId = new SelectList(db.LanguageInputs, "LanguageInputId", "Language");

            return View();
        }

        [HttpPost]
        public ActionResult Create(MasjidViewModel model, string Languageid, string design, string designname)
        {
            if (GetCitylists.lstWorldcity == null || GetCitylists.lstWorldcity.Count == 0)
            {
                GetCitylists.lstWorldcity = db.Worldcities.ToList();
            }
            List<Worldcity> cities = GetCitylists.lstWorldcity;
            var tempcityname = model.masjid.Cityname.ToLower().Trim();

            var cityobj = cities.Where(x => x.City.ToLower() == tempcityname).FirstOrDefault();
            if(cityobj != null)
            {
                //await GetNamaazTimeFromapi(model, cityobj);
            }
            Prayertime obj = model.prayertime;
            db.Prayertimes.Add(obj);
            db.SaveChanges();

            Masjid masjid = new Masjid();
            masjid.Masjidname = model.masjid.Masjidname;
            masjid.Cityname = model.masjid.Cityname;
            masjid.Designname = model.masjid.Designname;
            masjid.IsHorizontal = design == "horizontal" ? true : false;
            masjid.Languageid = Convert.ToInt32(Languageid);
            masjid.Prayertimeid = obj.Prayertimeid;
            db.Masjids.Add(masjid);
            db.SaveChanges();



            return View();
        }

        private static async Task GetNamaazTimeFromapi(MasjidViewModel model, Worldcity cityobj)
        {
            var lat = cityobj.Latitute.Value.ToString();
            var lng = cityobj.Longitude.Value.ToString();
            var method = "4";
            var month = DateTime.Now.Month.ToString();
            var year = DateTime.Now.Year.ToString();
            //var apicall = @" http://api.aladhan.com/v1/calendar?latitude=51.508515&longitude=-0.1254872&method=2&month=4&year=2017";
            //var apicall = @" http://api.aladhan.com/v1/hijriCalendarByCity?latitude="+lat+"&longitude="+lng+"&method="+method+"&month="+month+"&year="+year;
            var uristring = @"http://api.aladhan.com/v1/hijriCalendarByCity?";
            var values = @"city=" + model.masjid.Cityname + "&country=" + cityobj.Countryname + "&method=" + method + "&month=" + month + "&year=" + year;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(" http://api.aladhan.com/v1/hijriCalendarByCity");
                //HTTP GET
                var responseTask = await client.GetAsync(uristring + values);



                if (responseTask.IsSuccessStatusCode)
                {
                    var readTask = responseTask.Content.ReadAsStringAsync().Result;

                }
            }
        }


        [HttpPost]
        public JsonResult Getcities(string Prefix)
        {
            //Note : you can bind same list from database  
            if(GetCitylists.lstWorldcity == null || GetCitylists.lstWorldcity.Count == 0)
            {
                GetCitylists.lstWorldcity = db.Worldcities.ToList();
            }
            List<Worldcity> ObjList = GetCitylists.lstWorldcity;
            
            string lowprefix = Prefix.ToLower();
            //Searching records from list using LINQ query  
            var Name = (from N in ObjList
                        where N.City.ToLower().StartsWith(lowprefix)
                        select new { N.City });
            return Json(Name, JsonRequestBehavior.AllowGet);
        }

        public ActionResult EditPrayertime(int id)
        {
            var input = db.Masjids.Where(x => x.Masjidid == id).First();
            //var languages = db.LanguageInputs.ToList();
            var prayertimes = db.Prayertimes.Where(x => x.Prayertimeid == input.Prayertimeid.Value).First();

            Mosquedata model = new Mosquedata();
            model.Masjidid = input.Masjidid;
            model.Fajrazaan = prayertimes.Fajrazaan;
            model.Fajrnamaaz = prayertimes.Fajrnamaaz;
            model.Dhuhrazaan = prayertimes.Dhuhrazaan;
            model.Dhuhrnamaaz = prayertimes.Dhuhrnamaaz;
            model.Asrazaan = prayertimes.Asrazaan;
            model.Asrnamaaz = prayertimes.Asrnamaaz;
            model.Maghribazaan = prayertimes.Maghribazaan;
            model.Maghribnamaaz = prayertimes.Maghribnamaaz;
            model.Ishaazaan = prayertimes.Ishaazaan;
            model.Ishanamaaz = prayertimes.Ishanamaaz;
            model.AlJumuanamaaz = prayertimes.AlJumuanamaaz;
            model.Shuruq = prayertimes.Shuruq;
            

            return View(model);
        }

        [HttpPost]
        public ActionResult EditPrayertime(Mosquedata obj)
        {
            var input = db.Masjids.Where(x => x.Masjidid == obj.Masjidid).First();
            Prayertime t = db.Prayertimes.Where(x => x.Prayertimeid == input.Prayertimeid).First();

            
            t.Fajrazaan = obj.Fajrazaan;
            t.Fajrnamaaz = obj.Fajrnamaaz;
            t.Dhuhrazaan = obj.Dhuhrazaan;
            t.Dhuhrnamaaz = obj.Dhuhrnamaaz;
            t.Asrazaan = obj.Asrazaan;
            t.Asrnamaaz = obj.Asrnamaaz;
            t.Maghribazaan = obj.Maghribazaan;
            t.Maghribnamaaz = obj.Maghribnamaaz;
            t.Ishaazaan = obj.Ishaazaan;
            t.Ishanamaaz = obj.Ishanamaaz;
            t.AlJumuanamaaz = obj.AlJumuanamaaz;
            t.Shuruq = obj.Shuruq;
            db.Entry(t).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var input = db.Masjids.Where(x => x.Masjidid == id).First();
            ViewBag.LanguageInputId = new SelectList(db.LanguageInputs, "LanguageInputId", "Language");
            return View(input);
        }

        [HttpPost]
        public ActionResult Edit(Masjid obj, string Languageid, string design, string designname)
        {
            var input = db.Masjids.Where(x => x.Masjidid == obj.Masjidid).First();
            input.IsHorizontal = design == "horizontal" ? true : false;
            input.Languageid = Convert.ToInt32(Languageid);
            input.Designname = obj.Designname;
            db.Entry(input).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Mosqueapp/Views/Mosque/EditPrayertime.cshtml
@model Mosqueapp.Models.Mosquedata
@{
    ViewBag.Title = "EditPrayertime";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Edit Prayertime</h4>

@using (Html.BeginForm())
{

    @Html.HiddenFor(x => x.Masjidid)

    <div class="row" style="height:10px;">

    </div>
    
    <div class="row">
        <div class="col-md-4">
            <label style="color:black; font-size:16px;">Fajr timing </label>
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.Fajrazaan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Fajrazaan, new { htmlAttributes = new { @class = "form-control", id = "txtfajrazaan" } })
        </div>
        
        <div class="col-md-4">
            @Html.LabelFor(model => model.Fajrnamaaz, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Fajrnamaaz, new { htmlAttributes = new { @class = "form-control", id = "txtfajrnamaaz" } })
        </div>

    </div>
    
    <div class="row">
        <div class="col-md-4">
            <label style="color:black; font-size:16px;">Dhuhr timing </label>
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.Dhuhrazaan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Dhuhrazaan, new { htmlAttributes = new { @class = "form-control", id = "txtdhuhrazaan" } })
        </div>
        
        <div class="col-md-4">
            @Html.LabelFor(model => model.Dhuhrnamaaz, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Dhuhrnamaaz, new { htmlAttributes = new { @class = "form-control", id = "txtdhuhrnamaaz" } })
        </div>
    </div>

   
    <div class="row">
        <div class="col-md-4">
            <label style="color:black; font-size:16px;">Asr timing </label>
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.Asrazaan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Asrazaan, new { htmlAttributes = new { @class = "form-control", id = "txtasrazaan" } })
        </div>
        
        <div class="col-md-4">
            @Html.LabelFor(model => model.Asrnamaaz, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Asrnamaaz, new { htmlAttributes = new { @class = "form-control", id = "txtasrnamaaz" } })
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-4">
            <label style="color:black; font-size:16px;">Maghrib timing </label>
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.Maghribazaan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Maghribazaan, new { htmlAttributes = new { @class = "form-control", id = "txtmaghribazaan" } })
        </div>
       
        <div class="col-md-4">
            @Html.LabelFor(model => model.Maghribnamaaz, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Maghribnamaaz, new { htmlAttributes = new { @class = "form-control", id = "txtmaghribnamaaz" } })
        </div>
    </div>
  
    <div class="row">
        <div class="col-md-4">
            <label style="color:black; font-size:16px;">Isha timing </label>
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.Ishaazaan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Ishaazaan, new { htmlAttributes = new { @class = "form-control", id = "txtishaazaan" } })
        </div>
       
        <div class="col-md-4">
            @Html.LabelFor(model => model.Ishanamaaz, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Ishanamaaz, new { htmlAttributes = new { @class = "form-control", id = "txtishanamaaz" } })
        </div>
    </div>
    

    <div class="row">
        <div class="col-md-4">
            <label style="color:black; font-size:16px;">Jumua and Shuruq</label>
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.AlJumuanamaaz, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.AlJumuanamaaz, new { htmlAttributes = new { @class = "form-control", id = "txtjumanamaaz" } })
        </div>
        
        <div class="col-md-4">
            @Html.LabelFor(model => model.Shuruq, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Shuruq, new { htmlAttributes = new { @class = "form-control", id = "txtshuruqtime" } })
        </div>
    </div>

    <div class="row" style="height:30px;">

    </div>


    <div class="row">
        <div class="col-md-5"></div>
        <div class="col-md-2">
            <input type="submit" value="Save Prayertime" class="btn btn-primary" />
        </div>
        <div class="col-md-5"></div>
    </div>



}


<script type="text/javascript">
    $(document).ready(function () {
        $('#txtfajrazaan').timepicker();
        $('#txtfajrnamaaz').timepicker();
        $('#txtdhuhrazaan').timepicker();
        $('#txtdhuhrnamaaz').timepicker();
        $('#txtasrazaan').timepicker();
        $('#txtasrnamaaz').timepicker();
        $('#txtmaghribazaan').timepicker();
        $('#txtmaghribnamaaz').timepicker();
        $('#txtishaazaan').timepicker();
        $('#txtishanamaaz').timepicker();
        $('#txtjumanamaaz').timepicker();
        $('#txtshuruqtime').timepicker();


    });
</script>

Mosqueapp/Views/Mosque/Index.cshtml
@model IEnumerable<Mosqueapp.Models.mosquevm>

@{
    ViewBag.Title = "Mosque List";
    Layout = "~/Views/Shared/_Layout.cshtml";

    WebGrid webGrid = new WebGrid(Model);
}

<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .Grid {
        border: 1px solid #ccc;
        border-collapse: collapse;
    }

        .Grid th {
            background-color: #F7F7F7;
            font-weight: bold;
        }

        .Grid th, .Grid td {
            padding: 5px;
            border: 1px solid #ccc;
        }

        .Grid img {
            height: 150px;
            width: 150px;
            cursor: pointer;
        }

        .Grid, .Grid table td {
            border: 0px solid #ccc;
        }

            .Grid th a, .Grid th a:visited {
                color: #333;
            }
</style>
<h4>Mosque List</h4>

@webGrid.GetHtml(
    tableStyle: "table table-bordered table-striped mr",
    rowStyle: "gridrow",
    alternatingRowStyle: "gridalt",
        htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
        columns: webGrid.Columns(
                 webGrid.Column("Masjidname", "Mosquename"),
                 webGrid.Column("Cityname", "City"),
                 webGrid.Column("Designlayout", "Design Layout"),
                 webGrid.Column("Designname", "Design Name"),
                 webGrid.Column("Language", "Language"),
                 webGrid.Column("Imagepath", "Image",
                 format: @<text>
                    <img alt="@item.Masjidname" width="100" height="75"
                         src="@Url.Content(item.Imagepath)" />
                </text>),
webGrid.Column(columnName: "", format: (item) => Html.ActionLink("Edit Prayertimes", "EditPrayertime", "Mosque",
new { id = item.Masjidid }, null)),
webGrid.Column(columnName: "", format: (item) => Html.ActionLink("Edit", "Edit", "Mosque",
new { id = item.Masjidid }, null)),
webGrid.Column(columnName: "", format: (item) => Html.ActionLink("Delete", "Delete", "Mosque",
new { id = item.Masjidid }, null))

))