Mosqueapp/Models/Hadith.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mosqueapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hadith
    {
        public int Hadithid { get; set; }
        public string Hadith1 { get; set; }
    
        public virtual MosqueLink MosqueLink { get; set; }
    }
}

Mosqueapp/Controllers/HadithsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mosqueapp.Models;

namespace Mosqueapp.Controllers
{
    public class HadithsController : Controller
    {
        private mosqueappEntities db = new mosqueappEntities();

        // GET: Hadiths
        public ActionResult Index()
        {
            var hadiths = db.Hadiths.Include(h => h.MosqueLink);
            return View(hadiths.ToList());
        }

        // GET: Hadiths/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hadith hadith = db.Hadiths.Find(id);
            if (hadith == null)
            {
                return HttpNotFound();
            }
            return View(hadith);
        }

        // GET: Hadiths/Create
        public ActionResult Create()
        {
            ViewBag.Hadithid = new SelectList(db.MosqueLinks, "MosqueLinkid", "MosqueLinkid");
            return View();
        }

        // POST: Hadiths/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Hadithid,Hadith1")] Hadith hadith)
        {
            if (ModelState.IsValid)
            {
                db.Hadiths.Add(hadith);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Hadithid = new SelectList(db.MosqueLinks, "MosqueLinkid", "MosqueLinkid", hadith.Hadithid);
            return View(hadith);
        }

        // GET: Hadiths/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hadith hadith = db.Hadiths.Find(id);
            if (hadith == null)
            {
                return HttpNotFound();
            }
            ViewBag.Hadithid = new SelectList(db.MosqueLinks, "MosqueLinkid", "MosqueLinkid", hadith.Hadithid);
            return View(hadith);
        }

        // POST: Hadiths/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Hadithid,Hadith1")] Hadith hadith)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hadith).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Hadithid = new SelectList(db.MosqueLinks, "MosqueLinkid", "MosqueLinkid", hadith.Hadithid);
            return View(hadith);
        }

        // GET: Hadiths/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hadith hadith = db.Hadiths.Find(id);
            if (hadith == null)
            {
                return HttpNotFound();
            }
            return View(hadith);
        }

        // POST: Hadiths/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hadith hadith = db.Hadiths.Find(id);
            db.Hadiths.Remove(hadith);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mosqueapp/Views/Hadiths/Create.cshtml
@model Mosqueapp.Models.Hadith

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hadith</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Hadith1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hadith1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hadith1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mosqueapp/Views/Hadiths/Delete.cshtml
@model Mosqueapp.Models.Hadith

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hadith</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hadith1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hadith1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MosqueLink.MosqueLinkid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MosqueLink.MosqueLinkid)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Mosqueapp/Views/Hadiths/Details.cshtml
@model Mosqueapp.Models.Hadith

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Hadith</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hadith1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hadith1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MosqueLink.MosqueLinkid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MosqueLink.MosqueLinkid)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Hadithid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Mosqueapp/Views/Hadiths/Edit.cshtml
@model Mosqueapp.Models.Hadith

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hadith</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Hadithid)

        <div class="form-group">
            @Html.LabelFor(model => model.Hadith1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hadith1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hadith1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mosqueapp/Views/Hadiths/Index.cshtml
@model IEnumerable<Mosqueapp.Models.Hadith>

@{
    ViewBag.Title = "Hadith List";
    Layout = "~/Views/Shared/_Layout.cshtml";

    WebGrid webGrid = new WebGrid(Model);
}

<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .Grid {
        border: 1px solid #ccc;
        border-collapse: collapse;
    }

        .Grid th {
            background-color: #F7F7F7;
            font-weight: bold;
        }

        .Grid th, .Grid td {
            padding: 5px;
            border: 1px solid #ccc;
        }

        .Grid, .Grid table td {
            border: 0px solid #ccc;
        }

            .Grid th a, .Grid th a:visited {
                color: #333;
            }
</style>
<h4>Hadith List</h4>
<p>
    @Html.ActionLink("Add Hadith", "Create")
</p>

@webGrid.GetHtml(
    tableStyle: "table table-bordered table-striped mr",
    rowStyle: "gridrow",
    alternatingRowStyle: "gridalt",
        htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
        columns: webGrid.Columns(
                 webGrid.Column("Hadith1", "Hadith"),
                 webGrid.Column(columnName: "", format: (item) => Html.ActionLink("Edit", "Edit", "Hadiths",
new { id = item.Hadithid }, null)),
webGrid.Column(columnName: "", format: (item) => Html.ActionLink("Delete", "Delete", "Hadiths",
new { id = item.Hadithid }, null))

))